### ISSUE TITLE
Chip16 Filesystem

### ISSUE THREAD

**Issue by mwedmark** [chip16/chip16#17]
Support at least one external directory from which external files could be loaded into Chip16 mem would be nice. The implementation of a emulator could do whatever it like of course, but the simplest implementation would be to just map one directory on the physical drive.

Suggestion of minimal changes for most functionality:

GETFILE X,Y,Z - used to enumerate and "search" for files, also check sizes
X - Number of file to fetch from directory, used for enumeration, INPUT
Y- Holds the address where to put the name as a zero-terminated string, INPUT
Z - Size of file (up to 64K), OUTPUT

LOADFILE X,Y,Z - used to load files by name, f.e. one that is returned by GETFILE
X = Name zero-terminated string, INPUT
Y = Startaddress, INPUT
Z= Length of file, OUTPUT

SAVEFILE X,Y,Z - create a new file or overrite and old file.
X = Name zero-terminated string, INPUT
Y = Startaddress, INPUT
Z= Length of file, INPUT

**Comment by tykel** [comment]
I am going to close this as looking back at this, I think it's a bit convoluted.

Interacting with the host filesystem is definitely an interesting idea. I was thinking closer to designating a zone of the address space to be "extendable device memory", and if a peripheral or external file is "connected" to the emulator, reads and writes behave like memory-mapped I/O.
