### ISSUE TITLE
Time Management revisited

### ISSUE THREAD

**Issue by mwedmark** [chip16/chip16#19]
I couldn't add a comment to the old discussion so I started a new one. 
A sub-frame timer would keep track of how much time or how many instructions have elapsed since last Counter Reset sound useful. That is a tick counter either for instructions or us (which would actually be the same in this case..) could be quite nice. Could be used to keep track of frame rate for apps and usage of Chip16 resources. As a maximizing tool when trying optimize and keep 60 Hz or just for statistics.

**Comment by tykel** [comment]
I think a good compromise solution would be the introduction of interrupts, including a periodic one corresponding to HBLANK.
That would fire every 16666.66.../240 = 69.44444 cycles.

Alternatively, introduce a new register, TM, which gets incremented or decremented every cycle. Extend MOV to address that register.

**Comment by tykel** [comment]
I'll close this, but I might open a separate issue for a register which increments every cycle.
