### ISSUE TITLE
indirect addressing for PUSH/POP or read SP

### ISSUE THREAD

**Issue by mwedmark** [chip16/chip16#22]
When doing advanced libraries, I see the need for heavy stack usage. To keep all registers unaffected, an initial POP/PUSH of all registers used within the function is a must.

Then to make functions with in- and outparameters as generic as possible, these shall NOT use registers as their calling convention. Either using predetermined addresses for calling parameters to specific libraries or using stack seem to be the best possiblity. Both seem OK, but i really like the stack-based calling convention better. To be able to lift inparameters from stack to memory without destroying/using more registers, the use of especially PUSH (RX) and POP (RX) would help, which would use the address of RX to interact with the stack.

Is there a way to read the SP today? I know we can write to SP: LDI SP, HHLL
Maybe that could be useful to be able to read also?

**Comment by tykel** [comment]
Good candidate for the next revision of Chip16.

**Comment by prospero78** [comment]
Work with the stack pointer (and the stack as a whole) is mandatory in the processor. Direct loading of the contents of the stack register into any general register - such a command should be.
I disagree that using general purpose registers to pass parameters is a bad idea. The register-register command takes only one machine cycle, and in superscalar processors the instruction spacing is performed in different parts of the processor, which allows (for example) to execute 4 instructions per 1 clock cycle (if the selection from RAM allows you to prepare all the instructions that will be performed in a scalar way) . Moreover, when transferring control to another procedure - the calling code should not think about which registers should be kept - the code that receives the control flow should take care of this. Only this new code knows which registers it uses. And there may be several such places of transmission, which once again confirms the need to save the registers exactly with the code that takes control. In any case, you will have to use stack commands to support the old thread context. Therefore, do not be afraid to use parameter passing in registers. There is nothing bad.

**Comment by mwedmark** [comment]
This was though of as alternative when doing full context switching in this particular CPU, not as a suggestion of doing I7 quicker.. I just remember that when doing some more advanced stuff on this small platform I had problem to solved the above issues in an effective way, jumping between contexts.

Maybe it is like you say, just need to be smarter when using the already available commands. Because it is so long ago, I rest my case.

**Comment by tykel** [comment]
This is where calling conventions for functions step in: they specify which registers if any are used for parameters before using the stack, and which registers will be clobbered or not by function calls. See SysV or MSVC ABIs for x86, AMD64, ARM etc.

If you stick to whatever calling convention you decided upon, nothing more should be needed.

In theory, we do not even need `LDI SP, HHLL` as the same can be achieved by
```
LDI RX, HHLL
PUSH RX
RET
```
although admittedly that is 3 instructions versus 1...

As for `MOV RX, SP` to read back the stack pointer, I am struggling to see a real-world use case that necessitates it.
For now I will close this.
