### ISSUE TITLE
Current specification for CALL-RET behavior does not advance PC, resulting in endless loop

### ISSUE THREAD

**Issue by grigory-rechistov** [chip16/chip16#23]
This defect was discovered in the course of clean CHIP16 emulator implementation with Wind River Simics framework, using only wiki specifications.

An excerpt from current [Instructions list](Instructions):

| Opcode (Hex) | Mnemonic | Usage |
| --- | --- | --- |
| 14 00 LL HH | CALL HHLL | Store `PC` to `[SP]`, increase `SP` by 2, set `PC` to `HHLL`. |
| 15 00 00 00 | RET | Decrease `SP` by 2, set `PC` to `[SP]`. |

Let us consider a program with `CALL` and matching `RET` at the end of called subroutine.
1. During CALL, `PC` points to currently executed execution, that is, to CALL itself. This value is saved on the stack.
2. Execution goes to the subroutine entry point and proceeds through its body.
3. RET is encountered. It loads `PC` with a value from stack. But that previously saved value points to CALL itself, not to an instruction following it.
4. CALL gets executed again, resulting in the second transition to the subroutine. An endless loop is thus created.

The problem comes from the fact that CALL should have saved _PC+4_ on the stack, so that a subsequent instruction is fetched after RET.

My proposed fix to the specifications looks like this (the change is in bold):

| Opcode (Hex) | Mnemonic | Usage |
| --- | --- | --- |
| 14 00 LL HH | CALL HHLL | Store **PC+4** to `[SP]`, increase `SP` by 2, set `PC` to `HHLL`. |
| 15 00 00 00 | RET | Decrease `SP` by 2, set `PC` to `[SP]`. |

Other `CALL` variants are also affected and should be fixed as well.

Alternatively, `PC` could have been incremented by 4 at RET, not CALL, with the same net effect. Yet, the latter variant does not align well with CALL-RET semantics found in other CPU arhitectures.

**Comment by tykel** [comment]
> During CALL, PC points to currently executed execution, that is, to CALL itself. This value is saved on the stack.

Incorrect, PC holds the address of the next instruction to read, at PC+4.
An op execution goes:

- read instruction at PC..PC+3.
- PC := PC+4
- execute the instruction

I will add this explicitly to the wiki.
