### ISSUE TITLE
Current status of CHIP16

### ISSUE THREAD

**Issue by ghost** [chip16/chip16#25]
What is the current status of the CHIP16 project?

More specifically, when will the next specification (1.4) be released?

**Comment by mssenoga** [comment]
+1

**Comment by tykel** [comment]
Hello @ghost, Chip16 is in slowed development these days, as you can see from the activity here and on message boards.

My personal position is that I do still release new Chip16 demos/games and extend my emulator and tools.

I am planning a new revision sometime soon, I am unsure whether it will be 1.4 or 2.0 though.
